jobs:
  include:

    # tests for the domzzer-master-frontend
    - language: node_js
      node_js:
        - "stable"
      before_script:
        - cd ./domzzer-master-frontend
      script:
        - npm install
        - npm run build
        - npm run lint
        - npm run test
  
    # tests for the domzzer-master-backend
    - language: node_js
      node_js:
        - "stable"
      services:
        - mongodb
      before_script:
        - cd ./domzzer-master-backend
        - sleep 15
        - mongo domzzer_test --eval 'db.createUser({user:"admin",pwd:"admin",roles:["readWrite"]});'
      script:
        - npm install
        - npm run lint
        - npm run test

    # tests for the domzzer-slave-backend
    - language: python
      python: 3.6
      before_install:
        - cd ./domzzer-slave-backend
      install:
        - pip install -r requirements.txt    
      script:
        - echo "No tests"

