name: "Domzzer testing workflow"

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
    - uses: actions/checkout@v2

    # Test the master frontend

    # Test the master backend

    # Test the slave backend
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x 

    - name: Restore dependencies
      run: dotnet restore ./domzzer-slave-backend/
    
    - name: Build
      run: dotnet build ./domzzer-slave-backend/ -c Release --no-restore
    
    - name: Test
      run: dotnet test ./domzzer-slave-backend/ -c Release --no-build --verbosity normal

    # Test the slave fuzzer

