name: "Domzzer testing workflow"

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    defaults:
      run:
        shell: bash
    
    steps:
    - uses: actions/checkout@v2

    # Test the master frontend
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './domzzer-master-frontend/package-lock.json'
    
    - name: Navigate to correct directory
      run: cd ./domzzer-master-frontend/
    
    - name: Install
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Test
      run: npm test
    
    - name: Return to root folder
      run: cd ..

    # Test the master backend

    # Test the slave backend
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x 

    - name: Restore dependencies
      run: dotnet restore ./domzzer-slave-backend/
    
    - name: Build
      run: dotnet build ./domzzer-slave-backend/ -c Release --no-restore
    
    - name: Test
      run: dotnet test ./domzzer-slave-backend/ -c Release --no-build --verbosity normal

    # Test the slave fuzzer

