name: "Domzzer testing workflow"

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      MONGODB_URI: mongodb://admin:admin@localhost:27017/domzzer_test
      TEST_AES256_KEY: UjXn2r5u8x/A?D*G-KaPdSgVkYp3s6v9
      TEST_SECRET: Xn2r5u8x

    defaults:
      run:
        shell: bash
    
    steps:
    - uses: actions/checkout@v2

    # Test the master backend
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: 'domzzer-master-backend/package-lock.json'
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: '5.0'
        mongodb-username: admin
        mongodb-password: admin
        mongodb-db: domzzer_test

    - name: Install
      run: cd ./domzzer-master-backend/ && npm ci
    
    - name: Lint
      run: cd ./domzzer-master-backend/ && npm run lint
    
    - name: Test
      run: cd ./domzzer-master-backend/ && npm test

    # Test the master frontend
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: 'domzzer-master-frontend/package-lock.json'
  
    - name: Install
      run: cd ./domzzer-master-frontend/ && npm ci
    
    - name: Lint
      run: cd ./domzzer-master-frontend/ && npm run lint
    
    - name: Test
      run: cd ./domzzer-master-frontend/ && npm test

    # Test the slave backend
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x 

    - name: Restore dependencies
      run: dotnet restore ./domzzer-slave-backend/
    
    - name: Build
      run: dotnet build ./domzzer-slave-backend/ -c Release --no-restore
    
    - name: Test
      run: dotnet test ./domzzer-slave-backend/ -c Release --no-build --verbosity normal

    # Test the slave fuzzer

